name: Semantic Release

on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout the code
        uses: actions/checkout@main
        with:
          fetch-depth: 0

      - name: Set up uv
        uses: astral-sh/setup-uv@main

      - name: Run Semantic Release
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          uv run semantic-release -v version --skip-build --no-commit --no-tag --no-changelog
          uv lock
          git add uv.lock
          uv run semantic-release -v version
